### ISSUE TITLE
Dependency build issue: format.cc

### ISSUE THREAD

**Issue by DaulPavid** [rpclib/rpclib#109]
I'm running into a build error due to the format.cc dependency found [here](https://github.com/rpclib/rpclib/blob/master/dependencies/src/format.cc#L478):

> dependencies/src/format.cc:478:20: error: expected unqualified-id before numeric constant
> const unsigned CHAR_WIDTH = 1;

I think the bug has been addressed in a new version of this [dependency](https://github.com/fmtlib/fmt/issues/398).

Oh, I should mention this is on GCC 6.3.1.

**Comment by sztomi** [comment]
Thanks for reporting this issue. I'm wondering why this doesn't break on Travis though (it's gcc 6.2, but in one of the linked issues they mention 6.2 as well). Are you doing anything special or just a normal build via cmake && make?

**Comment by DaulPavid** [comment]
I'm just running a normal cmake && make. I am running on an updated Archlinux, though.

**Comment by sztomi** [comment]
Weird, I'm also building on Arch without any problems. Anyway, the fix easy and it's about time I update the bundled fmtlib, so it's coming soon.

**Comment by sztomi** [comment]
So right after upgrading my system I was able to reproduce the issue. I decided not to update fmtlib at this time, because the logging overhaul is coming later, and a full-blown update could be more difficult. So instead I just fixed the issue in the bundled copy. The fix is on the dev branch and coming in v1.1.0 (possibly this weekend).

**Comment by parasange** [comment]
Still having this problem of "expected unqualified-id" (linux410) with GCC 6.3.1

**Comment by sztomi** [comment]
@parasange what does `git rev-parse HEAD` say?

**Comment by parasange** [comment]
`git rev-parse HEAD` gives me:
a5dfa63ba1e52d637bd147d47e0ee6418acfc4d3

**Comment by sztomi** [comment]
@parasange in that case you need to update your local copy of the repo. (`git pull` on the master branch).

**Comment by parasange** [comment]
Sorry, but that didn't help. The error still occurs

**Comment by parasange** [comment]
Okay, thanks that works. Somehow AirSim just fetches an old commit of rpclib. Building it seperatley worked for me.

**Comment by sztomi** [comment]
It is possible that AirSim has not updated their submodule yet. I can't control that, so I suggest opening a ticket in their repo about this.

**Comment by parasange** [comment]
Ok, thanks anyways!
